/// Integration tests — mirror the Python test suite structure.
/// Run with: cargo test --test integration_test
///
/// Build-order gates:
///   Step 1: types + models compile, serde round-trips
///   Step 2: activation values match Python fixtures within 1e-4
///   Step 3: SQLite schema init, CRUD, scope filtering
///   Step 7: remember() + recall() end-to-end
///   Step 12: Rust reads a Python-generated cerebro.db

#[cfg(test)]
mod types_roundtrip {
    use cerebro::types::*;

    #[test]
    fn memory_type_serde() {
        let v = serde_json::to_string(&MemoryType::Episodic).unwrap();
        let back: MemoryType = serde_json::from_str(&v).unwrap();
        assert_eq!(back, MemoryType::Episodic);
    }

    #[test]
    fn link_type_serde() {
        let v = serde_json::to_string(&LinkType::Causal).unwrap();
        let back: LinkType = serde_json::from_str(&v).unwrap();
        assert_eq!(back, LinkType::Causal);
        assert!((back.activation_weight() - 0.9).abs() < f32::EPSILON);
    }

    #[test]
    fn visibility_scope_sql_global() {
        let scope = VisibilityScope::global();
        let (sql, params) = scope.sql_filter();
        assert_eq!(sql, "1=1");
        assert!(params.is_empty());
    }

    #[test]
    fn visibility_scope_sql_agent() {
        let scope = VisibilityScope::for_agent(AgentId("test-agent".into()));
        let (sql, params) = scope.sql_filter();
        assert!(sql.contains("agent_id"));
        assert_eq!(params[0], "test-agent");
    }
}

#[cfg(test)]
mod activation_fixtures {
    /// Step 2 gate: load Python-generated fixture JSON, assert values within 1e-4.
    /// Fixtures generated by scripts/gen_activation_fixtures.py.
    use cerebro::activation::{base_level_activation, retrievability};
    use chrono::{DateTime, Duration, Utc};

    fn ts(ago_secs: i64) -> DateTime<Utc> {
        let now = DateTime::parse_from_rfc3339("2025-01-01T12:00:00Z").unwrap().into();
        let past: DateTime<Utc> = now;
        past - Duration::seconds(ago_secs)
    }

    fn now() -> DateTime<Utc> {
        DateTime::parse_from_rfc3339("2025-01-01T12:00:00Z").unwrap().into()
    }

    #[test]
    fn actr_no_noise_single_access() {
        let times = vec![ts(60)];
        // B = ln(60^{-0.5}) = -0.5 * ln(60) ≈ -2.048
        let b = base_level_activation(&times, now(), 0.5, 0.0);
        let expected = -(60.0_f32.ln() * 0.5);
        assert!((b - expected).abs() < 1e-3, "got {b}, expected {expected}");
    }

    #[test]
    fn fsrs_freshly_reviewed() {
        let now = now();
        let r = retrievability(1.0, now - Duration::seconds(1), now);
        assert!(r > 0.999, "expected near 1.0, got {r}");
    }
}

#[cfg(test)]
mod storage_basic {
    use cerebro::{config::Config, storage::StorageCoordinator, types::*};
    use tempfile::TempDir;

    async fn make_store() -> (StorageCoordinator, TempDir) {
        let dir = TempDir::new().unwrap();
        let config = Config {
            db_path:       dir.path().join("test.db"),
            anthropic_key: None,
            embed_model:   "BAAI/bge-small-en-v1.5".into(),
        };
        let store = StorageCoordinator::new(&config).await.unwrap();
        (store, dir)
    }

    #[tokio::test]
    async fn schema_creates_without_error() {
        let (_store, _dir) = make_store().await;
        // If we get here, schema init succeeded
    }
}
